db.type=sqlite

db.mysql.url=jdbc:mysql://172.30.16.36:3306/db_ciberlight
db.sqlite.url=jdbc:sqlite:db_ciberlightsqlite

mongo.uri=mongodb://172.30.16.49:27017/?serverSelectionTimeoutMS=3000
mongo.database=ciberlight_backup
